config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-PROD
snowflake-account: ruflksm-ap56195
snowflake-database: PROD_DEFAULT_DB
snowflake-role: PROD_DEVOPS_FR
snowflake-user: PROD_DEVOPS_FR
snowflake-warehouse: DEFAULT_WH
root-folder: '$(System.DefaultWorkingDirectory)/migrations'
vars:
  ENVIRONMENT: 'PROD'
