config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-PROD
SF_ACCOUNT: ruflksm-ap56195
SF_DATABASE: PROD_DEFAULT_DB
PROJECT_FOLDER: $(System.DefaultWorkingDirectory)
SF_ROLE: PROD_DEVOPS_FR
SF_USERNAME: PROD_DEVOPS_FR
SF_WAREHOUSE: DEFAULT_WH
vars:
  ENVIRONMENT: 'PROD'
