config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-QA
SF_ACCOUNT: ruflksm-ap56195
SF_DATABASE: QA_DEFAULT_DB
PROJECT_FOLDER: $(System.DefaultWorkingDirectory)
SF_ROLE: QA_DEVOPS_FR
SF_USERNAME: QA_DEVOPS_FR
SF_WAREHOUSE: DEFAULT_WH
vars:
  ENVIRONMENT: 'QA'

