config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-QA
snowflake-account: ruflksm-ap56195
snowflake-database: QA_DEFAULT_DB
snowflake-role: QA_DEVOPS_FR
snowflake-user: QA_DEVOPS_FR
snowflake-warehouse: DEFAULT_WH
root-folder: '$(System.DefaultWorkingDirectory)/migrations'
vars:
  ENVIRONMENT: 'QA'

