config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-QA
snowflake-account: 'ruflksm-ap56195'
snowflake-database: 'QA_DEFAULT_DB'
snowflake-role: 'QA_DEVOPS_FR'
snowflake-user: 'QA_DEVOPS_FR'
snowflake-warehouse: 'DEFAULT_WH'
root-folder: 'migrations'
change-history-table: 'QA_DEFAULT_DB.SCHEMACHANGE.CHANGE_HISTORY'
create-change-history-table: true
modules-folder: 'modules'
vars:
  ENVIRONMENT: 'QA'

