
jobs:
  - job: dryrun_qa
    displayName: "DRYRUN-QA"
    variables:
      - group: snowflake-variables-qa
  
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: '3.8'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Starting bash task'
          echo "PROJECT_FOLDER $(PROJECT_FOLDER)"
          python --version
          echo 'Step 1: Installing schemachange'
          pip install schemachange --upgrade
          echo 'Step 2: Running schemachange'
          schemachange --config-folder $(System.DefaultWorkingDirectory)/configurations/schemachange_config/SNOWFLAKE-IAC-QA --dry-run
      env:
        SNOWFLAKE_PASSWORD: $(SF_PASSWORD)    

  - job: dryrun_prod
    displayName: "DRYRUN-PROD"
    variables:
      - group: snowflake-variables-prod
      
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: '3.8'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Starting bash task'
          echo "PROJECT_FOLDER $(PROJECT_FOLDER)"
          python --version
          echo 'Step 1: Installing schemachange'
          pip install schemachange --upgrade
          echo 'Step 2: Running schemachange'
          schemachange --config-folder $(System.DefaultWorkingDirectory)/configurations/schemachange_config/SNOWFLAKE-IAC-PROD --dry-run
      env:
        SNOWFLAKE_PASSWORD: $(SF_PASSWORD)