parameters:
  - name: PROJECT_FOLDER
    type: string
  - name: SF_ACCOUNT
    type: string
  - name: SF_DATABASE
    type: string
  - name: SF_PASSWORD
    type: string
  - name: SF_ROLE
    type: string
  - name: SF_USERNAME
    type: string
  - name: SF_WAREHOUSE
    type: string
  - name: ENVIRONMENT
    type: string
  - name: ROOT_FOLDER
    type: string
  - name: SCHEMA
    type: string


jobs:
  - deployment: env_deployment
    displayName: "Environment Deployment"
    environment: ${{parameters.ENVIRONMENT}}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.8'
            inputs:
              versionSpec: '3.8'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Starting bash task'
                echo "PROJECT_FOLDER ${{parameters.PROJECT_FOLDER}}"
                python --version
                echo 'Step 1: Installing schemachange'
                pip install schemachange --upgrade
                echo 'Step 2: Running schemachange'
                schemachange -f ${{parameters.ROOT_FOLDER}} -a ${{parameters.SF_ACCOUNT}} --vars $(ENV_VARIABLES) -u ${{parameters.SF_USERNAME}} -r ${{parameters.SF_ROLE}} -w ${{parameters.SF_WAREHOUSE}} -d ${{parameters.SF_DATABASE}} -c ${{parameters.SF_DATABASE}}.SCHEMACHANGE.${{parameters.SCHEMA}}_CHANGE_HISTORY --create-change-history-table
            env:
              SNOWFLAKE_PASSWORD: ${{parameters.SF_PASSWORD}}